import type { Metadata } from "next";
import "./globals.css";
import ConfigureAmplifyClientSide from "@/config/amplify.config";
import { dmSans, spaceMono } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${spaceMono.variable} font-sans antialiased`}
      >
        {children}

        <ConfigureAmplifyClientSide />
      </body>
    </html>
  );
}
